// Country code → display name, backed by the DISCOVERED placeSources registry
// (src/data/placeSources/index.json, generated by scripts/buildPlaceSources.ts).
// Pure + dependency-free (a static JSON import, no fs) so it works identically on
// the client (story screen) and the server (synthesis payload). This replaces the
// old hand-curated zone labels: conflict "sides" are now keyed by ISO 3166-1
// alpha-2 country code, and the label comes from the same registry that supplies
// the outlets — so there is no separate hand-maintained list to drift.

import countryIndex from "../data/placeSources/index.json";

/** cc (lowercase ISO-2) → { label, continent, … } from the discovered registry. */
const INDEX = countryIndex as Record<string, { label?: string } | undefined>;

/**
 * Human label for an ISO 3166-1 alpha-2 code, e.g. "ua" → "Ukraine". Falls back to
 * the upper-cased code for countries the discovery pipeline hasn't catalogued, and
 * to "International" for an absent/global token (mirrors the old zoneLabel default).
 */
export function countryLabel(cc: string | undefined | null): string {
  if (!cc || cc === "international") return "International";
  const code = cc.toLowerCase().slice(0, 2);
  return INDEX[code]?.label ?? cc.toUpperCase();
}
