// Centralized in-app navigation helpers (route-based, so the browser's virtual
// history works — back/forward and deep-links).
//
// Expo Router's typed-route literals are GENERATED by `expo start`; in tooling /
// CI that generated declaration can lag behind newly-added route files. To keep
// `tsc` stable regardless of typegen freshness, we funnel every push through this
// module and assert the well-known `Href` shape in ONE place. Keep the paths here
// correct — this is the single source of truth for cross-screen links.

import { router, type Href } from "expo-router";

/** Open the full-screen in-app reader for a news item (/news/[id]). */
export function openNews(id: string): void {
  router.push(`/news/${encodeURIComponent(id)}` as Href);
}

/** Open the developing-issue / story panel (/story/[id]). */
export function openStory(id: string): void {
  router.push(`/story/${encodeURIComponent(id)}` as Href);
}

/** Go back if possible, else fall back to the main tabs. */
export function goBack(): void {
  if (router.canGoBack()) router.back();
  else router.replace("/(tabs)" as Href);
}
