// DATA-DRIVEN geographic tree, built ENTIRELY from the discovered placeSources —
// there are no hardcoded countries or regions anywhere. The shape is:
//
//   world → continent → country → region
//
// Inputs (all generated by scripts/buildPlaceSources.ts, never hand-edited):
//   src/data/placeSources/<cc>.json   — the country's discovered outlets, each
//                                        optionally tagged with an ISO 3166-2
//                                        `region` (+ `regionLabel`).
//   src/data/placeSources/index.json  — cc → { label, continent, continentLabel }
//                                        so countries group under their continent.
//
// From these we synthesize the node tree:
//   - countries  = the <cc>.json files present;
//   - continents = the distinct `continent` slugs in the index;
//   - regions    = the distinct `region` codes tagged on a country's outlets.
//
// A node's outlets are the country's set, NARROWED to the region for region nodes
// (true region discovery). The whole tree is cached for the process lifetime and
// rebuilt only when the underlying files change (or in tests via the hooks below).

import { existsSync, readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import type { Source } from "../src/types";
import { GEO_ROOT_ID, type GeoNode } from "../src/data/geo";

/** Whether (and how well) a node is covered by discovered outlets. */
export type CoverageState = "ready" | "none" | "unknown";

/** Generated per-country metadata (placeSources/index.json). */
interface CountryMeta {
  label: string;
  continent?: string;
  continentLabel?: string;
}

interface Tree {
  byId: Map<string, GeoNode>;
  children: Map<string, GeoNode[]>;
  sourcesByCc: Map<string, Source[]>;
}

let placeSourcesDir = resolve(process.cwd(), "src/data/placeSources");
let cache: Tree | null = null;

/** Test-only: point the builder at a fixture directory (clears the cache). */
export function _setPlaceSourcesDir(dir: string): void {
  placeSourcesDir = dir;
  cache = null;
}

/** Test-only: drop the cached tree (e.g. after writing new placeSources). */
export function _clearGeoTreeCache(): void {
  cache = null;
}

/** Accent/space-insensitive slug for stable node ids ("ES-GA" → "es-ga"). */
function slug(s: string): string {
  return s
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function readJson<T>(path: string): T | null {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf8")) as T;
  } catch (e) {
    console.warn(`[geoTree] failed to parse ${path}:`, e instanceof Error ? e.message : e);
    return null;
  }
}

function build(): Tree {
  const byId = new Map<string, GeoNode>();
  const children = new Map<string, GeoNode[]>();
  const sourcesByCc = new Map<string, Source[]>();

  const add = (n: GeoNode): void => {
    if (byId.has(n.id)) return;
    byId.set(n.id, n);
    if (n.parent) {
      const arr = children.get(n.parent) ?? [];
      arr.push(n);
      children.set(n.parent, arr);
    }
  };

  add({ id: GEO_ROOT_ID, level: "world", label: "World" });

  const index = readJson<Record<string, CountryMeta>>(resolve(placeSourcesDir, "index.json")) ?? {};
  const files = existsSync(placeSourcesDir)
    ? readdirSync(placeSourcesDir).filter((f) => /^[a-z]{2}\.json$/.test(f))
    : [];

  for (const file of files) {
    const cc = file.slice(0, 2);
    const sources = readJson<Source[]>(resolve(placeSourcesDir, file)) ?? [];
    sourcesByCc.set(cc, sources);
    const meta = index[cc];

    // Country attaches under its continent when known, else directly under world.
    let parentId = GEO_ROOT_ID;
    if (meta?.continent) {
      if (!byId.has(meta.continent)) {
        add({
          id: meta.continent,
          parent: GEO_ROOT_ID,
          level: "continent",
          label: meta.continentLabel || meta.continent,
        });
      }
      parentId = meta.continent;
    }
    add({ id: cc, parent: parentId, level: "country", label: meta?.label || cc.toUpperCase(), country: cc });

    // Regions = the distinct ISO 3166-2 codes tagged on this country's outlets.
    const regions = new Map<string, string>(); // code → label
    for (const s of sources) {
      if (s.region && !regions.has(s.region)) regions.set(s.region, s.regionLabel || s.region);
    }
    for (const [code, label] of regions) {
      add({ id: slug(code), parent: cc, level: "region", label, country: cc, regionCode: code });
    }
  }

  return { byId, children, sourcesByCc };
}

function tree(): Tree {
  if (!cache) cache = build();
  return cache;
}

/** Resolve a node by id (undefined if unknown). */
export function geoNode(id: string | null | undefined): GeoNode | undefined {
  return id ? tree().byId.get(id) : undefined;
}

/** Direct children of a node (empty if leaf/unknown). */
export function childrenOf(id: string | null | undefined): GeoNode[] {
  return (id && tree().children.get(id)) || [];
}

/** Ancestor chain from the root down to `id` (inclusive). Empty if unknown. */
export function pathOf(id: string | null | undefined): GeoNode[] {
  const out: GeoNode[] = [];
  let cur = geoNode(id);
  const guard = new Set<string>();
  while (cur && !guard.has(cur.id)) {
    out.push(cur);
    guard.add(cur.id);
    cur = cur.parent ? geoNode(cur.parent) : undefined;
  }
  return out.reverse();
}

/** Display label for a node id (falls back to the id itself). */
export function geoLabel(id: string | null | undefined): string {
  return geoNode(id)?.label ?? (id ?? "");
}

/**
 * Outlets for a geo node: the country's discovered outlets, NARROWED to the
 * region for region nodes (region discovery). World/continent nodes serve nothing
 * directly — the reader drills into a country/region.
 */
export function sourcesForGeoNode(id: string | null | undefined): Source[] {
  const node = geoNode(id);
  if (!node || !node.country) return [];
  const all = tree().sourcesByCc.get(node.country) ?? [];
  return node.regionCode ? all.filter((s) => s.region === node.regionCode) : all;
}

/** Whether a geo node has any discovered coverage (colors the navigation map). */
export function coverageStateOf(id: string | null | undefined): CoverageState {
  const node = geoNode(id);
  if (!node) return "unknown";
  if (node.level === "world" || node.level === "continent") return "unknown"; // drill in
  return sourcesForGeoNode(id).length > 0 ? "ready" : "unknown";
}
