// Server-side PLACE GAZETTEER loader. Returns the alias gazetteer (PlaceNode[])
// for a country, used to compute the geographic relevance BOOST in feedService.
//
// Resolution order per country code:
//   1. src/data/gazetteer/<cc>.json  — generated by scripts/buildGazetteer.ts
//      (rich, from GeoNames). Preferred when present.
//   2. Built-in SEED below — a small hand-seeded fallback so the place lens works
//      out of the box for the primary market (Spain) before the importer is run.
//
// Results are cached per country for the process lifetime.

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { PlaceNode } from "../src/types";
import { SEED_GAZETTEER } from "../src/data/places";

const cache = new Map<string, PlaceNode[]>();

/** Gazetteer nodes for a country code (generated file preferred, else seed, else empty). */
export function gazetteerFor(country: string | undefined | null): PlaceNode[] {
  const cc = (country ?? "").toLowerCase().slice(0, 2);
  if (!cc) return [];
  const hit = cache.get(cc);
  if (hit) return hit;

  let nodes: PlaceNode[] = [];
  const file = resolve(process.cwd(), "src/data/gazetteer", `${cc}.json`);
  if (existsSync(file)) {
    try {
      const parsed = JSON.parse(readFileSync(file, "utf8"));
      if (Array.isArray(parsed)) nodes = parsed as PlaceNode[];
    } catch (e) {
      console.warn(`[places] failed to parse ${file}:`, e instanceof Error ? e.message : e);
    }
  }
  if (nodes.length === 0) nodes = SEED_GAZETTEER[cc] ?? [];
  cache.set(cc, nodes);
  return nodes;
}

/** Test-only: drop the cached gazetteers. */
export function _clearGazetteerCache(): void {
  cache.clear();
}
