// Streams a single country's Admin-1 (province/state) border polygons to the globe.
//
// The slim Natural Earth Admin-1 set lives server-side (server/data/admin1-10m.json,
// generated by scripts/buildAdmin1.mjs) and is NEVER bundled into the app. The whole
// file is parsed once on first request and indexed by ISO-2 country code; the app
// then fetches just the country the reader opens via GET /api/regions?cc=es.
//
// Each feature is already slimmed to { iso2, code (ISO 3166-2), name } + geometry, so
// the globe can match a region to its coverage node via slug(code) ("ES-GA" → "es-ga").

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

export interface RegionFeature {
  /** `group`/`groupCode` are the higher-level division name + code (e.g. a Spanish
   *  province's autonomous community) — coverage is often keyed at THAT level, so the
   *  globe binds a province to its covered region by either. */
  properties: { iso2: string; code: string; name: string; group?: string; groupCode?: string };
  geometry: { type: "Polygon" | "MultiPolygon"; coordinates: unknown } | null;
}

interface RegionFile {
  features: RegionFeature[];
}

const dataPath = resolve(process.cwd(), "server/data/admin1-10m.json");
let byCc: Map<string, RegionFeature[]> | null = null;

function load(): Map<string, RegionFeature[]> {
  if (byCc) return byCc;
  const m = new Map<string, RegionFeature[]>();
  if (!existsSync(dataPath)) {
    console.warn(`[regions] ${dataPath} not found — run scripts/buildAdmin1.mjs. Regions disabled.`);
    byCc = m;
    return m;
  }
  try {
    const file = JSON.parse(readFileSync(dataPath, "utf8")) as RegionFile;
    for (const f of file.features ?? []) {
      const cc = f.properties?.iso2;
      if (!cc) continue;
      const arr = m.get(cc) ?? [];
      arr.push(f);
      m.set(cc, arr);
    }
    console.log(`[regions] loaded ${file.features?.length ?? 0} provinces for ${m.size} countries`);
  } catch (e) {
    console.warn("[regions] failed to parse admin1 data:", e instanceof Error ? e.message : e);
  }
  byCc = m;
  return m;
}

/** The province/state polygons for a country (ISO-2, case-insensitive); [] if none. */
export function getRegions(cc: string): { features: RegionFeature[] } {
  return { features: load().get(cc.toLowerCase()) ?? [] };
}
