// Generate a human-readable report of the geographic ZONES we cover reactively
// (and the original-language outlets in each). Run with: `npm run report:zones`.
// Writes docs/COVERAGE.md and prints a summary. Sourced directly from
// src/data/zones.ts so the report can never drift from the actual registry.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { ZONES } from "../src/data/zones";

/** Human language names for the ISO 639-1 codes we use. */
const LANG_NAMES: Record<string, string> = {
  en: "English",
  uk: "Ukrainian",
  ru: "Russian",
  zh: "Chinese",
  he: "Hebrew",
  ar: "Arabic",
  fa: "Persian",
  hi: "Hindi",
  ur: "Urdu",
  tr: "Turkish",
  es: "Spanish",
  pt: "Portuguese",
  fr: "French",
  ja: "Japanese",
  ko: "Korean",
};

const langName = (code: string): string => LANG_NAMES[code] ?? code;

function buildReport(): { markdown: string; summary: string } {
  const allSources = ZONES.flatMap((z) => z.sources);
  const allLangs = new Set(allSources.map((s) => s.lang ?? "en"));
  const originalLangSources = allSources.filter((s) => (s.lang ?? "en") !== "en");

  const lines: string[] = [];
  lines.push("# Geographic coverage");
  lines.push("");
  lines.push(
    "Reactive international zones loaded **on demand** when a live story involves them " +
      "(see `src/data/zones.ts`). Each zone carries English-edition outlets **and " +
      "original-language outlets**, so we capture how a story is told inside a country, " +
      "not just its export-facing English coverage.",
  );
  lines.push("");
  lines.push("> Auto-generated by `npm run report:zones`. Do not edit by hand.");
  lines.push("");
  lines.push("## At a glance");
  lines.push("");
  lines.push(`- **Zones covered:** ${ZONES.length}`);
  lines.push(`- **Total outlets:** ${allSources.length}`);
  lines.push(
    `- **Original-language outlets:** ${originalLangSources.length} of ${allSources.length}`,
  );
  lines.push(
    `- **Languages:** ${[...allLangs]
      .map(langName)
      .sort()
      .join(", ")}`,
  );
  lines.push("");

  // Coverage matrix.
  lines.push("## Coverage matrix");
  lines.push("");
  lines.push("| Zone | Outlets | Languages |");
  lines.push("| --- | ---: | --- |");
  for (const z of ZONES) {
    const langs = [...new Set(z.sources.map((s) => s.lang ?? "en"))].map(langName).join(", ");
    lines.push(`| ${z.label} | ${z.sources.length} | ${langs} |`);
  }
  lines.push("");

  // Per-zone detail.
  lines.push("## Outlets by zone");
  lines.push("");
  for (const z of ZONES) {
    const langs = [...new Set(z.sources.map((s) => s.lang ?? "en"))];
    lines.push(`### ${z.label}`);
    lines.push("");
    lines.push(`*Languages:* ${langs.map(langName).join(", ")}`);
    lines.push("");
    lines.push(`*Detection aliases:* ${z.aliases.join(", ")}`);
    lines.push("");
    lines.push("| Outlet | Language | Affiliation |");
    lines.push("| --- | --- | --- |");
    for (const s of z.sources) {
      lines.push(`| ${s.title} | ${langName(s.lang ?? "en")} | ${s.leanRationale} |`);
    }
    lines.push("");
  }

  const markdown = lines.join("\n");

  const summary =
    `Zones: ${ZONES.length} | Outlets: ${allSources.length} ` +
    `(original-language: ${originalLangSources.length}) | ` +
    `Languages: ${[...allLangs].map(langName).sort().join(", ")}`;

  return { markdown, summary };
}

const { markdown, summary } = buildReport();
const out = resolve(process.cwd(), "docs/COVERAGE.md");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, markdown + "\n", "utf8");
console.log(`Wrote ${out}`);
console.log(summary);
